# Dockerfile.frontend
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Install dependencies
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy Streamlit app to container
COPY ./frontend/streamlit_app.py /app/streamlit_app.py

# Run Streamlit app
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]

